"""Central pin mapping for the Zilena robot hardware."""

# RGB LED (digital outputs)
RGB_LED_RED_PIN = 21
RGB_LED_GREEN_PIN = 11
RGB_LED_BLUE_PIN = 10

# Serial LEDs (NeoPixel)
SERIAL_LED_DATA_PIN = 8

# Motors (H-bridge PWM inputs)
MOTOR_RIGHT_FORWARD_PIN = 19
MOTOR_RIGHT_BACKWARD_PIN = 18
MOTOR_LEFT_FORWARD_PIN = 20
MOTOR_LEFT_BACKWARD_PIN = 22

# OLED display (I2C)
OLED_SCL_PIN = 7
OLED_SDA_PIN = 6

# Sensors
PHOTORESISTOR_ADC_PIN = 3
ULTRASOUND_TRIG_PIN = 15
ULTRASOUND_ECHO_PIN = 23

# Music
BUZZER_PIN = 5

# Robot controls
MUSIC_STOP_BUTTON_PIN = 2
