song_titles = [
    'Star Trek intro',
    'Silent Night',
    'Pacman',
    'Ode an die Freude',
    'Star Wars theme',
    "Wiegenlied (Brahms' Lullaby)",
    'Theme A from Tetris (Korobeiniki)',
    'Happy Birthday',
    'Dart Vader theme',
    'Nokia Ringtone',
    'Mii Channel theme',
    'Minuet in G - Petzold',
    'Badinerie - Johann Sebastian Bach',
    'Für Elise - Ludwig van Beethoven',
    'Cantina Band (Star wars)',
    'Song of storms (The Legend of Zelda, Ocarina of Time)',
    'The Lion Sleeps Tonight',
    'The Lick',
    'Canon in D - Pachelbel',
    "At Doom's Gate (E1M1)",
    'Pink Panther theme',
    "Hedwig's theme (Harry Potter)",
    "Jigglypuff's Song",
    'We Wish You a Merry Christmas',
    'Keyboard cat',
    'Game of Thrones',
    'Greensleeves',
    'Green Hill Zone - Sonic the Hedgehog',
    'The Legend of Zelda theme',
    'Baby Elephant Walk',
    'Bloody Tears (Castlevania II)',
    'O Pulo da Gaita (Auto da Compadecida)',
    'Vampire Killer (Castlevania)',
    'Never Gonna Give You Up - Rick Astley',
    'Take on me - A-ha',
    'Prince Igor - Polovtsian Dances, Borodin',
    "Zelda's Lullaby - The Legend of Zelda, Ocarina of Time",
    'Super Mario Bros theme, by Koji Kondo',
    'Asa branca - Luiz Gonzaga',
    'The Godfather theme',
    "Professor Layton's theme",
    'Coalescence ',
]
